import { Payment, columns } from "./columns";
import { DataTable } from "./data-table";

const getData = async (): Promise<Payment[]> => {
  return [
    {
      id: "728ed521",
      amount: 134,
      status: "pending",
      fullName: "John Doe",
      email: "johndoe@gmail.com",
      userId: "1001",
    },
    {
      id: "728ed522",
      amount: 124,
      status: "success",
      fullName: "Jane Doe",
      email: "janedoe@gmail.com",
      userId: "1002",
    },
    {
      id: "728ed523",
      amount: 167,
      status: "success",
      fullName: "Mike Galloway",
      email: "mikegalloway@gmail.com",
      userId: "1003",
    },
    {
      id: "728ed524",
      amount: 156,
      status: "failed",
      fullName: "Minerva Robinson",
      email: "minerbarobinson@gmail.com",
      userId: "1004",
    },
    {
      id: "728ed525",
      amount: 145,
      status: "success",
      fullName: "Mable Clayton",
      email: "mableclayton@gmail.com",
      userId: "1005",
    },
    {
      id: "728ed526",
      amount: 189,
      status: "pending",
      fullName: "Nathan McDaniel",
      email: "nathanmcdaniel@gmail.com",
      userId: "1006",
    },
    {
      id: "728ed527",
      amount: 178,
      status: "success",
      fullName: "Myrtie Lamb",
      email: "myrtielamb@gmail.com",
      userId: "1007",
    },
    {
      id: "728ed528",
      amount: 190,
      status: "success",
      fullName: "Leona Bryant",
      email: "leonabryant@gmail.com",
      userId: "1008",
    },
    {
      id: "728ed529",
      amount: 134,
      status: "failed",
      fullName: "Aaron Willis",
      email: "aaronwillis@gmail.com",
      userId: "1009",
    },
    {
      id: "728ed52a",
      amount: 543,
      status: "success",
      fullName: "Joel Keller",
      email: "joelkeller@gmail.com",
      userId: "1010",
    },
    {
      id: "728ed52b",
      amount: 234,
      status: "pending",
      fullName: "Daniel Ellis",
      email: "danielellis@gmail.com",
      userId: "1011",
    },
    {
      id: "728ed52c",
      amount: 345,
      status: "success",
      fullName: "Gordon Kennedy",
      email: "gordonkennedy@gmail.com",
      userId: "1012",
    },
    {
      id: "728ed52d",
      amount: 335,
      status: "failed",
      fullName: "Emily Hoffman",
      email: "emilyhoffman@gmail.com",
      userId: "1013",
    },
    {
      id: "728ed52e",
      amount: 664,
      status: "pending",
      fullName: "Jeffery Garrett",
      email: "jefferygarrett@gmail.com",
      userId: "1014",
    },
    {
      id: "728ed52f",
      amount: 332,
      status: "success",
      fullName: "Ralph Baker",
      email: "ralphbaker@gmail.com",
      userId: "1015",
    },
    {
      id: "728ed52g",
      amount: 413,
      status: "failed",
      fullName: "Seth Fields",
      email: "sethfields@gmail.com",
      userId: "1016",
    },
    {
      id: "728ed52h",
      amount: 345,
      status: "pending",
      fullName: "Julia Webb",
      email: "juliawebb@gmail.com",
      userId: "1017",
    },
    {
      id: "728ed52i",
      amount: 754,
      status: "success",
      fullName: "Gary Banks",
      email: "garybanks@gmail.com",
      userId: "1018",
    },
    {
      id: "728ed52j",
      amount: 643,
      status: "failed",
      fullName: "Flora Chambers",
      email: "florachambers@gmail.com",
      userId: "1019",
    },
    {
      id: "728ed52k",
      amount: 543,
      status: "pending",
      fullName: "Steve Hanson",
      email: "stevehanson@gmail.com",
      userId: "1020",
    },
    {
      id: "728ed52l",
      amount: 324,
      status: "success",
      fullName: "Lola Robinson",
      email: "lolarobinson@gmail.com",
      userId: "1021",
    },
    {
      id: "728ed52m",
      amount: 123,
      status: "pending",
      fullName: "Ethel Waters",
      email: "ethelwaters@gmail.com",
      userId: "1022",
    },
    {
      id: "728ed52n",
      amount: 422,
      status: "failed",
      fullName: "Grace Edwards",
      email: "graceedwards@gmail.com",
      userId: "1023",
    },
    {
      id: "728ed52o",
      amount: 712,
      status: "success",
      fullName: "Sallie Wong",
      email: "salliewong@gmail.com",
      userId: "1024",
    },
    {
      id: "728ed52p",
      amount: 360,
      status: "success",
      fullName: "Bryan Gutierrez",
      email: "bryangutierrez@gmail.com",
      userId: "1025",
    },
    {
      id: "728ed52q",
      amount: 454,
      status: "pending",
      fullName: "Erik Rice",
      email: "erikrice@gmail.com",
      userId: "1026",
    },
    {
      id: "728ed52r",
      amount: 382,
      status: "success",
      fullName: "Jordan Atkins",
      email: "jordanatkins@gmail.com",
      userId: "1027",
    },
    {
      id: "728ed52s",
      amount: 328,
      status: "failed",
      fullName: "Bill Brewer",
      email: "billbrewer@gmail.com",
      userId: "1028",
    },
    {
      id: "728ed52t",
      amount: 250,
      status: "success",
      fullName: "Edwin Morris",
      email: "edwinmorris@gmail.com",
      userId: "1029",
    },
    {
      id: "728ed52u",
      amount: 658,
      status: "success",
      fullName: "Harold Becker",
      email: "haroldbecker@gmail.com",
      userId: "1030",
    },
    {
      id: "728ed52v",
      amount: 691,
      status: "success",
      fullName: "Hannah Rodriguez",
      email: "hannahrodriguez@gmail.com",
      userId: "1031",
    },
    {
      id: "728ed52w",
      amount: 969,
      status: "success",
      fullName: "Zachary Beck",
      email: "zacharybeck@gmail.com",
      userId: "1032",
    },
    {
      id: "728ed52x",
      amount: 617,
      status: "failed",
      fullName: "Frances Potter",
      email: "francespotter@gmail.com",
      userId: "1033",
    },
    {
      id: "728ed52y",
      amount: 173,
      status: "success",
      fullName: "Raymond Murray",
      email: "raymondmurray@gmail.com",
      userId: "1034",
    },
    {
      id: "728ed52z",
      amount: 843,
      status: "success",
      fullName: "Adam Sherman",
      email: "adamsherman@gmail.com",
      userId: "1035",
    },
    {
      id: "728ed521f",
      amount: 914,
      status: "pending",
      fullName: "Anne Cruz",
      email: "annecruz@gmail.com",
      userId: "1036",
    },
  ];
};

const PaymentsPage = async () => {
  const data = await getData();
  return (
    <div className="">
      <div className="mb-8 px-4 py-2 bg-secondary rounded-md">
        <h1 className="font-semibold">All Payments</h1>
      </div>
      <DataTable columns={columns} data={data} />
    </div>
  );
};

export default PaymentsPage;
